name: 🦍 Despliegue

on:
  push:
    branches: [main]

jobs:
  build:
    name: 🐘 Desplegar
    runs-on: ubuntu-latest

    steps:
      - name: 🐯 Obtener código del repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🐜 Activar Corepack
        run: corepack enable

      - name: 🐝 Usar Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - name: 🦒 Instalar dependencias y hacer build
        run: |
          yarn install --immutable
          yarn build
      - name: 🦅 Enviar por SFTP
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: ${{ secrets.DOMINIO_IMAGINA }}
          username: ${{ secrets.USUARIO_IMAGINA }}
          password: ${{ secrets.CLAVE_IMAGINA }}
          localDir: 'aplicaciones/www/publico'
          remoteDir: '/srv/www/wordpress/especiales/prevalence-csea/'
          removeExtraFilesOnServer: true
